### PR TITLE
Update cloud-digital-leader.md

### PR DESCRIPTION
**Pull request by Ahmed0028**

### CODE REVIEW

**Comment by Ahmed0028** [comment]
Google Cloud Digital Leader Exam is now General Available.

**Review by sathishvj — COMMENTED** [review]
Where is the practice exam available?  Can you share the link?

**Comment by Ahmed0028** [comment]
Sure Thing! 

Reg Link: 
https://cloud.google.com/certification/cloud-digital-leade  



image

**Comment by Ahmed0028** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSfexWKtXT2OSFJ-obA4iT3GmzgiOCGvjrT9OfxilWC1yPtmfQ/viewform

**Comment by Ahmed0028** [comment]
Sorry. I mean the reg Exam is now GA and not the Practical exam itself.

**Comment by sathishvj** [comment]
The GA of the exam has already been updated in this repo.  So that's already taken care of.
Since there is no practice exam yet, I'll have to reject this pull request.

Still, thank you for the attempt at improving this repo.  Please continue to do that.

**Pull request closed without merging**
