### PR TITLE
Updated associate-cloud-engineer.md with articles published recently

### PR DESCRIPTION
**Pull request by viveknaskar**

### CODE REVIEW

**Comment by rishiraj88** [comment]
Thanks

**Comment by viveknaskar** [comment]
Can you merge this PR?

**Review by sathishvj — COMMENTED** [review]
The edit adds one line, but it seems to be changing multiple lines. Instead of adding this edit or asking you to redo this, I've added the entry myself in a different commit. 
I'll close this.

**Comment by viveknaskar** [comment]
Thank you, @sathishvj! 

> The edit adds one line, but it seems to be changing multiple lines. Instead of adding this edit or asking you to redo this, I've added the entry myself in a different commit. I'll close this.

Thank you, @sathishvj! That will do!

**Pull request closed without merging**
